import { NextRequest, NextResponse } from 'next/server';
import { desc, eq } from 'drizzle-orm';
import { db } from '@/db';
import { contactInquiries, inquiryNotes, users } from '@/db/schema';
import { withRole } from '@/lib/auth/middleware';
import { inquiryPatchSchema } from '@/lib/validation/inquiries';

export const GET = withRole(['admin', 'sales', 'service_technician'], async (_request: NextRequest, _auth, context: { params: Promise<{ id: string }> }) => { const id = Number((await context.params).id); const [inquiry] = await db.select({ id: contactInquiries.id, inquiryNumber: contactInquiries.inquiryNumber, fullName: contactInquiries.fullName, phone: contactInquiries.phone, email: contactInquiries.email, subject: contactInquiries.subject, message: contactInquiries.message, status: contactInquiries.status, assignedStaffId: contactInquiries.assignedStaffId, assignedStaffName: users.name, createdAt: contactInquiries.createdAt }).from(contactInquiries).leftJoin(users, eq(users.id, contactInquiries.assignedStaffId)).where(eq(contactInquiries.id, id)).limit(1); if (!inquiry) return NextResponse.json({ error: 'Inquiry not found' }, { status: 404 }); const notes = await db.select().from(inquiryNotes).where(eq(inquiryNotes.inquiryId, id)).orderBy(desc(inquiryNotes.createdAt)); return NextResponse.json({ inquiry, notes }); });
export const PATCH = withRole(['admin', 'sales', 'service_technician'], async (request: NextRequest, { user }, context: { params: Promise<{ id: string }> }) => { const id = Number((await context.params).id); const parsed = inquiryPatchSchema.safeParse(await request.json()); if (!parsed.success || !id) return NextResponse.json({ error: 'Invalid inquiry update' }, { status: 400 }); const { note, ...data } = parsed.data; const [inquiry] = await db.transaction(async (tx) => { const [updated] = await tx.update(contactInquiries).set({ ...data, updatedAt: new Date() }).where(eq(contactInquiries.id, id)).returning(); if (note) await tx.insert(inquiryNotes).values({ inquiryId: id, note, createdBy: user.userId }); return [updated]; }); return NextResponse.json({ inquiry }); });
