import { pgTable, serial, varchar, text, integer, timestamp, index, uniqueIndex } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './users';
import { serviceTickets } from './services';

export const contactInquiries = pgTable('contact_inquiries', {
  id: serial('id').primaryKey(),
  /**
   * Generated by Postgres, not by the app.
   *
   * The default is `'INQ-' || year || '-' || lpad(nextval(...), 6, '0')` — see
   * migration 0002. Declaring the default here is what makes the column optional
   * on insert, so callers omit it and cannot reintroduce a colliding value.
   */
  inquiryNumber: varchar('inquiry_number', { length: 30 })
    .notNull()
    .default(sql`'INQ-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('contact_inquiry_number_seq')::text, 6, '0')`),
  fullName: varchar('full_name', { length: 150 }).notNull(),
  phone: varchar('phone', { length: 15 }).notNull(),
  email: varchar('email', { length: 200 }),
  subject: varchar('subject', { length: 120 }).notNull(),
  message: text('message').notNull(),
  status: varchar('status', { length: 20 }).notNull().default('UNREAD'),
  assignedStaffId: integer('assigned_staff_id').references(() => users.id, { onDelete: 'set null' }),
  convertedServiceId: integer('converted_service_id').references(() => serviceTickets.id, { onDelete: 'set null' }),
  convertedLeadId: integer('converted_lead_id'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (t) => ({ numberIdx: uniqueIndex('contact_inquiries_number_idx').on(t.inquiryNumber), statusIdx: index('contact_inquiries_status_idx').on(t.status), createdIdx: index('contact_inquiries_created_idx').on(t.createdAt) }));

export const inquiryNotes = pgTable('inquiry_notes', {
  id: serial('id').primaryKey(),
  inquiryId: integer('inquiry_id').notNull().references(() => contactInquiries.id, { onDelete: 'cascade' }),
  note: text('note').notNull(),
  createdBy: integer('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
}, (t) => ({ inquiryIdx: index('inquiry_notes_inquiry_idx').on(t.inquiryId, t.createdAt) }));

export const salesLeads = pgTable('sales_leads', {
  id: serial('id').primaryKey(),
  leadNumber: varchar('lead_number', { length: 30 }).notNull(),
  fullName: varchar('full_name', { length: 150 }).notNull(),
  phone: varchar('phone', { length: 15 }).notNull(),
  email: varchar('email', { length: 200 }),
  request: text('request').notNull(),
  status: varchar('status', { length: 20 }).notNull().default('OPEN'),
  createdBy: integer('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});
